version: '3.8'

services:
  redis:
    image: redis:7  
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./ 
    container_name: backend1
    network_mode: host
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://localhost:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_data: